#!/usr/bin/env python3

# This library is under the 3-Clause BSD License
#
# Copyright (c) 2025, Orange
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#    * Neither the name of Orange nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL ORANGE BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# SPDX-License-Identifier: BSD-3-Clause
# Software Name: MetAMoRphosED AMR-Editor
# Author: Johannes Heinecke

# read standard AMR format and produce UMR format (notably for alignments)

import re
import sys

import penman

import metamorphosed.amrdoc as amrdoc


class AMR2UMR:
    def __init__(self, infile, outfile, first=0, last=0, filterid=None, gen=True):
        adoc = amrdoc.AMRdoc(infile)
        if filterid:
            filterid = re.compile(filterid)

        ofp = open(outfile, "w")
        if gen:
            print("# generated by:", " ".join(sys.argv), file=ofp)
        for ct, sent in enumerate(adoc.sentences, 1):
            if ct < first:
                continue
            if last != 0 and ct > last:
                continue
            if filterid:
                if not filterid.match(sent.id):
                    continue
            # read id, sentence and AMR
            # extract alignments if present
            # rename variables

            print("#" * 80, file=ofp)
            print("# meta-info :: sent_id =", sent.id, file=ofp)
            print("# :: snt%d" % ct, file=ofp)
            for c in sent.comments:
                print("#", c, file=ofp)
            if sent.tokens:
                print("Index:", "\t".join([str(x + 1) for x in range(len(sent.tokens))]), file=ofp)
                print("Words:", "\t".join(sent.tokens), file=ofp)
            elif sent.text:
                print("Index:", "\t".join([str(x + 1) for x in range(len(sent.text.split()))]), file=ofp)
                print("Words:", "\t".join(sent.text.split()), file=ofp)
            print("Sentence:", sent.text, file=ofp)
            amr, alignments, ralignments, lalignments = self.umrise(ct, sent.amr)

            print("# sentence level graph:", file=ofp)
            print(amr, file=ofp)
            print("\n", file=ofp)

            print("# alignment:", file=ofp)
            for k, vv in alignments.items():
                #if "-" in k:
                #    # RoleAlignments not available in UMR
                #    print("#RA ", end="", file=ofp)
                print("%s: " % k, end="", file=ofp)
                print(", ".join(["%d-%d" % (x[0], x[1]) for x in vv]), file=ofp)
            for k, vv in ralignments.items():
                # RoleAlignments not available in UMR
                print("#RA %s: " % k, end="", file=ofp)
                print(", ".join(["%d-%d" % (x[0], x[1]) for x in vv]), file=ofp)
            for k, vv in lalignments.items():
                # Literal Alignments not available in UMR
                print("#LA %s: " % "#".join(k), end="", file=ofp)
                print(", ".join(["%d-%d" % (x[0], x[1]) for x in vv]), file=ofp)
            print("\n", file=ofp)

            print("# document level annotation:", file=ofp)
            print("\n", file=ofp)

    def umrise(self, nr, pm):
        pg = penman.decode(pm)

        newvars = {} # old: new
        newtriples = []
        for s, p, o in pg.triples:
            if s in pg.variables():
                s2 = "s%d%s" % (nr, s)
                newvars[s] = s2
                s = s2
            if p != ":instance" and o in pg.variables():
                o2 = "s%d%s" % (nr, o)
                newvars[o] = o2
                o = o2
            newtriples.append((s, p, o))

        alignments = {} # var: [(from, to), ...]
        ralignments = {} # varfrom-varto: [(from, to), ...]
        lalignments = {} # literal: [(from, to), ...]
        for tr,eds in pg.epidata.items():
            s2 = newvars.get(tr[0], tr[0])
            o2 = newvars.get(tr[2], tr[2])
            for ed in eds:
                if isinstance(ed, penman.surface.AlignmentMarker):
                    #print("  ", ed, ed.mode, ed.indices)
                    if ed.mode == 1: # RoleAlignment
                        edge = s2 + "-" + o2
                        for ix1 in ed.indices:
                            ix = ix1 + 1
                            if edge not in ralignments:
                                ralignments[edge] = [(ix, ix)]
                            else:
                                ralignments[edge].append((ix, ix))
                    else: # Alignment:
                        for ix1 in ed.indices:
                            ix = ix1 + 1
                            if tr[1] == ":instance":
                                if s2 not in alignments:
                                    alignments[s2] = [(ix, ix)]
                                else:
                                    alignments[s2].append((ix, ix))
                            else:
                                key = (s2, tr[1][1:], o2)
                                if key not in lalignments:
                                    lalignments[key] = [(ix, ix)]
                                else:
                                    lalignments[key].append((ix, ix))

        return penman.encode(penman.Graph(newtriples), indent=4), alignments, ralignments, lalignments


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser("AMR2UMR transformation")

    parser.add_argument("--infile", "-i", required=True, help="AMR input file to read")
    parser.add_argument("--outfile", "-o", required=True, help="UMR output file")
    parser.add_argument("--first", "-f", default=0, type=int, help="start at sentence number <first>")
    parser.add_argument("--last", "-l", default=0, type=int, help="stop after sentence number <last>")
    parser.add_argument("--filterid", "-F", help="ignore sentences which sentence id does not mutch given regex")

    if len(sys.argv) < 2:
        parser.print_help()
    else:
        args = parser.parse_args()
        a2u = AMR2UMR(args.infile, args.outfile, args.first, args.last, args.filterid)
